---
id: 201711-componentization-via-services
base_name: 201711-componentization-via-services
tags:
- rabbit
- microservices
- architecture
- component
- services
presentation_date: 2017-11-27
version: 2017.11.01.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
